### PR TITLE
Replace preferences to style for loop statements

### PR DESCRIPTION
**Pull request by ikokostya**
Instead of deleting `loop` section I added style guides for loop statements. 

Related with https://github.com/ymaps/codestyle/pull/28

### CODE REVIEW

**Comment by tarmolov** [comment]
:+1:

**Comment by dmikis** [comment]
Is there any other way to write a loop in JS? The sections seem redundant to me.

**Comment by ikokostya** [comment]
> Is there any other way to write a loop in JS?

```js
while {
}
do ()
```

**Comment by dmikis** [comment]
The first one isn't actually syntacticly correct. As for the second one, we already have rules to forbid it.

**Comment by ikokostya** [comment]
> The first one isn't syntacticly correct.

I mean do..while 

```js
do {
}
while ()
```

> As for the second one, we already have rules to forbid it.

We have only https://github.com/ymaps/codestyle/blob/master/javascript.md#keywords

> Keywords are always followed by a single space character:

But we have not rule for space before `{` or after `;` in `for`

**Comment by dmikis** [comment]
> But we have not rule for space before { or after ; in for statement.
Yes, we do for opening curly braces: https://github.com/ymaps/codestyle/blob/master/javascript.md#block-statements

**Comment by dmikis** [comment]
I'm long overdue with the comment I've promised. Sorry.

I suggest we also provide a recommendation on formatting long `for` statements. For example:

```
for (
    var i = getLevelIdxStart(currentSubdivLevel),
        iEnd = getLevelIdxEnd(currentSubdivLevel);
    i < iEnd;
    ++i
) {
```

or

```
for (
    offsetEnd = offset + length,
        offset1 = offset % length,
            offset2 = (offset + 2) % length;
    offset < offsetEnd;
    offset += 2,
        offset1 = offset % length,
              = (offset + 2) % length
 ) {
```

**Comment by ikokostya** [comment]
In first example I suggest move long statments from `for`:

```js
var i = getLevelIdxStart(currentSubdivLevel);
var iEnd = getLevelIdxEnd(currentSubdivLevel);
for ( ; i < iEnd; ++i) {
    // do example
}
```

In second example:

* Move initialization of `offset1` and `offset2` from `for`
* Move updating of `offset1` and `offset2` variables to `for body`

  ```js
  var offsetEnd = offset + length;
  var offset1 = offset % length;
  var offset2 = (offset + 2) % length;
  for ( ; offset < offsetEnd; offset += 2) {
     // do somethind

      offset1 = offset % length;
      offset2 = (offset + 2) % length;
  }
  ```

I think that `for` should not contain complicated expressions. If you need its, then
* move its outside;
* or move it to functions;
* or use `while` instead `for` .

**Comment by dmikis** [comment]
:shipit:

**Pull request merged**
