### PR TITLE
Remove preferences for loop statements

### PR DESCRIPTION
**Pull request by vtambourine**
I have removed preferences on loop statements due to its weak relevance to actual style of the code. See https://github.com/yandex/codestyle/issues/22#issuecomment-68100302.

### CODE REVIEW

**Comment by alt-j** [comment]
If you want remove some rules, you must do it in both translations.

**Comment by vtambourine** [comment]
Do you mean I miss something?

**Comment by alt-j** [comment]
@vtambourine, I'm so sorry. I didn't see changes in the second file.

lgtm

**Comment by ikokostya** [comment]
See https://github.com/ymaps/codestyle/pull/58

**Pull request closed without merging**
