### PR TITLE
jscs-preset: add jscs as peer dependency

### PR DESCRIPTION
**Pull request by ikokostya**
@tarmolov

### CODE REVIEW

**Comment by dodev** [comment]
:-1: 
Please take a look at the NOTE in the [npm's peerDependencies documentation](https://docs.npmjs.com/files/package.json#peerdependencies) - `peerDependencies` are deprecated in npm@3. I personally had to deal with dependency hell caused by contradicting peerDependencies of two packages.

**Comment by ikokostya** [comment]
> peerDependencies are deprecated in npm@3.

peerDependencies are not deprecated. `npm@3` doesn't automatically install peerDependencies. 

How we should declare that preset may not work with `jscs < 2.4`?

**Comment by dmikis** [comment]
As a dependency? Seems OK to me: there is no sane situation when you need the preset, but not `jscs` itself.

**Comment by ikokostya** [comment]
> As a dependency?

As peer dependency, because you may update `jscs` without `preset`.

**Comment by ikokostya** [comment]
Also you can use another plugins. Therefore dependency from `jscs` inside preset isn't good solution.

**Pull request merged**
