### PR TITLE
eslint-config: add more rules

### PR DESCRIPTION
**Pull request by ikokostya**

### CODE REVIEW

**Comment by tarmolov** [comment]
It's hard to validate all new added rules manually. Maybe it's better to add some tests to validate eslint config?

**Comment by ikokostya** [comment]
I have no idea how do it right:
* using one "correct" file we can't test prohibiting rules;
* it is not so easy write this file, because we have `unsued variable` rules etc.

We can create directories with samples which should pass validation and with samples which should not:

```
test/
  samples/
    success/
       classes.js
       ...
    fail/
       unused-vars.js
       ...
```
But this tests duplicate `eslint`'s tests.

**Comment by ikokostya** [comment]
I can add short comment for each rule. Maybe it solves problem.

**Comment by tarmolov** [comment]
I don't want to duplicate eslint docs, too ^^

I think it's a problem when you add a lot of rules. It means that probably we don't have the same problem in the future.

:ok:

**Pull request merged**
